name: linux

on: push

defaults:
  run:
    shell: bash
    working-directory: fire_atlas_editor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux 
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: fa_linux
          path: fire_atlas_editor/build/linux/x64/release/bundle
