name: linux

on: push

defaults:
  run:
    shell: bash
    working-directory: fire_atlas_editor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux 



