name: mac

on: push

defaults:
  run:
    shell: bash
    working-directory: fire_atlas_editor

jobs:
  needs: lint
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: fa_osx
          path: fire_atlas_editor/build/macos/Build/Products/Release/Fire\ Atlas\ Editor.app



