name: windows

on: push

defaults:
  run:
    shell: bash
    working-directory: fire_atlas_editor

jobs:
  build:
    needs: lint
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: fa_windows
          path: fire_atlas_editor/build/windows/runner/Release
